version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/StudentFeedbackSentimentAnalysis
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=aayush
      - ML_SERVICE_URL=http://ml-proxy:8080
    depends_on:
      - db
      - ml-proxy

  ml-service:
    build: ./ai_model
    volumes:
      - ./ai_model/model:/app/model
    environment:
      - FLASK_ENV=production

  ml-proxy:
    image: nginx:alpine
    ports:
      - "5000:8080"
    volumes:
      - ./ai_model/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - ml-service

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=StudentFeedbackSentimentAnalysis
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=aayush
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
